spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  redis:
    host: ${REDIS_HOST:ourlog-redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

cookie:
  secure: true

app:
  sql:
    lineMonthly: "DATE_FORMAT(d.created_at, '%Y-%m')"
    lineDaily: "DATE_FORMAT(d.created_at, '%Y-%m-%d')"